port=53
address=/app.wiretitan.test/10.7.12.247
address=/api.wiretitan.test/10.7.12.247
listen-address=127.0.0.1,10.7.6.126
bind-interfaces
server=8.8.8.8
server=1.1.1.1
log-queries
log-facility=/tmp/dnsmasq.log
